### ISSUE TITLE
Identify alternatives and decide on a PDF generator

### ISSUE THREAD

**Issue by OddArneSaetervik** [Altinn/altinn-pdf#16]
Selvfølgelig vil dette være avhenging av hvordan HTML ene blir seende ut. 
Altså hvor rike de kan komme til å være.
Dette antar vi vil komme til å bli avklart på #13 

Identifiserte kandidater er:
- https://itextpdf.com/en/products/itext-7/convert-html-css-to-pdf-pdfhtml
- https://www.puppeteersharp.com/
- Finne ut hvilke bibliotek/applikasjon som brukes av Altinn 2. Potensielt benytte Altinn 2 sin PDF tjeneste?
- Issuet har også rom for å lete etter andre kandidater.
 
Avslutningsvis må man bestemme seg for hvilket alternativ man skal kjøre PoC på

### Licensing
Open source always come with a license. We must consider each one if we do decide on an open source product. Open source products can sometimes also have bought versions we could consider.

### Rendering
There are primarily two type of products. The product has its own HTML renderer. The other kind of product use an integrated (or external) browser to perform the rendering and a "save as PDF" type of mechanism. This last type of product will probably always render something closer to what the user would see in a browser.

### Input types
The tools will either take an HTML document or a URL, or both as input.

### PDF/A AND UA
For tools that don't support PDF/A, it might be possible to use a third tool like [ghostscript](https://ghostscript.com/). Another important standard is UA (universal accessibility). [More info...](https://pdf.abbyy.com/learning-center/pdf-standards/#:~:text=%E2%80%9CUA%E2%80%9D%20stands%20for%20%E2%80%9CUniversal,who%20depends%20on%20these%20technologies.) [Even more info...](https://www.pdfa.org/wp-content/until2016_uploads/2013/08/PDFUA-in-a-Nutshell-PDFUA.pdf)

### Vekt
Output must be PDF-A3/UA 60%
implementasjon effort 20%
cost 20%

### Candidates
Tool | License | Rendering  |  Input | PDF/A | PDF/UA | Comment
-----|---------|--------------|--------|---------|--------|-----
[iText](https://itextpdf.com/en) Paid | Paid | Custom? | HTML | Yes | [Yes](https://www.nuget.org/packages/itext7/) | € 6540,-/1 year for 60 000 PDF. Need quote for higher volumes.
[Puppeteer Sharp](https://github.com/hardkoded/puppeteer-sharp) | MiT | Browser| URL | No | ? | Small "private" project. Active with release 7.0 in april.
[Syncfusion](https://www.syncfusion.com/document-processing/pdf-framework/net) | Paid | Chromium/ QtWebkit | Both | Yes | [Yes](https://www.syncfusion.com/document-processing/pdf-framework/net/pdf-library/accessible-pdf) | Developer packs too small (5). Need quote for project license.
[IronPdf](https://ironpdf.com/tutorials/html-to-pdf/) | Paid | Chromium | Both | [No](https://ironpdf.com/docs/questions/pdfa/) | [Yes](https://ironpdf.com/docs/questions/create-accessible-pdfs-508-c-sharp/) | Developer licenses. $ 3000,- No limit, perpetual. Support $ 400,- per year.
[PDFReactor](https://www.pdfreactor.com/) | Paid | Custom? | URL | Yes | [Yes](https://www.pdfreactor.com/pdfua/) | CPU cores licenses. This means simultaneous PDF conversions. If we have multiple machines we would need multiple licenses. Available as a cloud service and as a Java library.
[ExpertPdf](https://www.html-to-pdf.net/html-to-pdf-converter.aspx) | Paid | Custom? | Both | No? | ? | Unable to find any information about accessibility support. 

### Discarded candidates
Tool | Comment
-----|-------
[iText](https://itextpdf.com/en) OS | The Open Source variant of this library has an aggressive license. The AGPL license makes it hard to use it as open source as it could force us to use the AGLP license as well.
[EO.Pdf](https://www.essentialobjects.com/#Pdf) | Can't find any new documentation about EO supporting accessibility or is able to produce tags for a text reader. [No support](https://www.essentialobjects.com/forum/postst11927_HTML-to-PDF-tags-for-accessibility.aspx)?
[SelectPdf](https://selectpdf.com/pdf-library-for-net/) | There is a free community edition version, but it looks like there is a limit to 5 pages. Requires a full version Windows as it relies on system [libraries](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) not available in Core or Nano. We want a lightweight OS for our containers.
[dompdf](https://dompdf.github.io/) | PHP application. Can load HTML and output a PDF. Does not support adding [tags](https://github.com/dompdf/dompdf/issues/2774) (accessibility).
[wkhtmltopdf](https://wkhtmltopdf.org/) | Command line tool. Might be a [dieing project](https://wkhtmltopdf.org/status.html). Excluding because of the uncertain future.

**Comment by bengtfredh** [comment]
Et par verktøy man kan ta med i vurderingen:
https://github.com/dompdf/dompdf  # HTML to PDF converter
https://wkhtmltopdf.org/  # command line tools to render HTML into PDF

**Comment by tba76** [comment]
Altinn 2 bruker Essential Objects sin pdf-løsning. https://www.essentialobjects.com/#Pdf

**Comment by olemartinorg** [comment]
Jeg kan nevne at jeg har hatt gode erfaringer tidligere med `wkhtmltopdf`. Det er prinsipielt et ganske enkelt verktøy, og det blir omtrent det samme som å printe en nettside fra Chrome. Det gir i alle fall mye fleksibilitet uten at man trenger å lære seg et eget bibliotek spesifikt for å lage PDFer.

**Comment by elsand** [comment]
SelectPDF er Windows-only, og bruker System.Drawing-API-ene. Disse er ikke tilgjengelig på Windows Server Core eller Windows Nano (https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=net-6.0) så denne tror jeg ikke er aktuell.

**Comment by SandGrainOne** [comment]
Vi jobber litt med å se etter alternative biblioteker eller verktøy for å generere PDF. Vi har dokumentert det meste i en issue i [altinn-pdf](https://github.com/Altinn/altinn-pdf/issues/16) repo.

**Comment by elsand** [comment]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Er muligens andre av de .NET-baserte på lista som benytter System.Drawing, som da i praksis betyr windows-only. Bruk av libgdiplus som workaround på Linux fjernes fra .NET7. (SelectPDF har i tillegg bindinger til kernel32.dll)

Forøvrig verdt å merke seg det som nevnes på https://wkhtmltopdf.org/status.html, nemlig at man ikke kan bruke dette på "untrusted html". Dette gjelder nok i en eller annen grad for alle bibliotekene som tar html/css/js som input. Hvis dette er tenkt som en sentral service, vil kreve kontroll på hvorvidt appene kan direkte påvirke hvordan html-en blir generert - om de skal ha det i det hele tatt. Dette må da balanseres opp mot appenes behov for fleksibilitet i hvordan pdf-ene blir generert.

**Comment by elsand** [comment]
Har testet litt med IronPDF. Denne bruker også som default Chromium behind the scenes. I utgangspunktet henter den ned Chrome og andre dependencies runtime(!), som ble en smule knot å få til med permissions etc i Docker. Men man kan hente inn en spesialversjon av nuget-en, `IronPdf.Linux` samt den rendreren en går for, f.eks. `IronPdf.Native.Chrome.Linux`, som da sørger for å hente alt ved byggetid. Dette fører til at det legges inn en `runtimes`-mappe i output, som inneholder binaries herunder Chrome. `/app/runtimes/linux-x64/native` er 411MB på imaget. 

Ting jeg noterte meg:

* Alpine er IKKE støttet pga. at musl ikke støttes av Chromium. Jeg brukte i stedet `-focal`-taggen på imagene som hentes, som er Ubuntu 20.
* Ethvert forsøk på kjøretids installasjon av assets feiler, ikke alltid med meningsfulle meldinger i Insights. Dette må deaktiveres ref. https://ironpdf.com/docs/questions/docker-linux/ (sett `IrontPdf.Installation.LinuxAndDockerDependenciesAutoConfig=false;`
* Dockerfile må inneholde `RUN chmod 755 runtimes/linux-x64/native/IronCefSubprocess`
* Jeg er usikker på hvor trådsikkert og skalerbart dette er, siden det brukes en subprosess, men virker å være ganske raskt

Ellers nyttig info: 
* https://ironpdf.com/docs/questions/docker-linux/ 
* https://ironpdf.com/docs/questions/azure/
* https://ironpdf.com/docs/questions/linux/

**Comment by SandGrainOne** [comment]
Foreløpig IronPdf og iText som kanskje peker seg ut så langt. Veldig bra at du tester ut IronPdf.

**Comment by SandGrainOne** [comment]
Quote HansO
> HTML to PDF på server-side er et lite monster.
> Er skeptisk til at en app-utvikler plutselig kan ta over platform-klusteret ved en sårbarhet i pdf-generatoren.
> Sååå mye trust har vi ikke i dem

**Comment by altinnadmin** [comment]
My thoughts...

## Principles for PDF generation

### PDF generation should "just work"
*When new UI components, widgets, page layouts, process steps, dynamics, translations or other new app features are
introduced, PDFs should be generated without requiring additional effort.*

How to achieve this:
- The apps must produce the HTML that is to be converted to PDF
- This is the same HTML that is produced when a user opens an app in a browser, and it opens up the possibility of
  generating PDFs for all kind of app pages
- PDF generation must use a widely used browser engine for rendering.  
  [Chromium](https://en.wikipedia.org/wiki/Chromium_(web_browser)) is the most popular engine in the world by far.

### PDFs should look good
*When creating an app with a nice responsive user interface, the generated PDF should automatically reflect this interface.*

How to achieve this:
- We use [print CSS](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing) to optimize print and PDF
- App developers use our[grid system](https://docs.altinn.studio/nb/app/development/ux/styling/#sidestilte-komponenter-grid) to optimize the responsive layout for various sizes, including print/PDF.
- PDF generation must use a modern browser engine for rendering.  Chromium-based browsers have been [in the lead](https://html5test.com/results/desktop.html) for a long time.

### PDFs should be accessible
*The generated PDFs must be accessible and follow WCAG and the [requirements for PDF/UA](https://en.wikipedia.org/wiki/PDF/UA#Requirements_for_conforming_PDF_files_(Clause_7))*

How to achieve this:
- Focus on [WCAG 2.1](https://www.w3.org/TR/WCAG21/) support in the app front-end. This is the foundation.
- Generate [tagged](https://en.wikipedia.org/wiki/PDF#Logical_structure_and_accessibility) PDFs from the app HTML. [Headless Chrome supports this](https://blog.chromium.org/2020/07/using-chrome-to-generate-more.html).
- Embed fonts in PDF. This is also a central requirement for [PDF/A](https://en.wikipedia.org/wiki/PDF/A).

### PDF generation should be scalable and robust
*Generating PDFs can be heavy, typically consuming a lot of compute and memory. When load increases, PDF generation needs to scale automatically, and scaling should only impact the relevant app owner.*

How to achieve this:
- We run the PDF generator in containers running in each apps cluster, like KubernetesWrapper
- We should not run PDF generation as part of the apps
- When load increases, pods and nodes for only the relevant app owner can scale automatically, independent of Platform
- This means cost related to PDF-generation is directly linked to the cluster of the app owner

### PDF generation should be secure
*Rendering HTML and running javascript server side in a browser is a security challenge, since we can't trust the HTML. This challenge needs to be handled.*

How to achieve this:
- We run the PDF generator in containers running in each apps cluster, isolating rendering of HTML from Platform
- [Chromium implements a sandbox](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/design/sandbox.md)
- A container is also a kind of sandbox that can be hardened
- Patching of Chromium needs to be done continuously
- We should limit the allowed URL input
- Authentication needs to be handled

### PDF generation should follow the Altinn 3 architecture principles
*Altinn 3 is following a set of [architecture principles](https://docs.altinn.studio/principles/), PDF generation should do that as well.*

Relavant Altinn 3 principles:
- [Free and open-source software](https://docs.altinn.studio/technology/architecture/principles/#free-and-open-source-software)
  - [Chromium is open source](https://www.chromium.org/Home/) 
- [Isolation](https://docs.altinn.studio/technology/architecture/principles/#isolation). See chapter above.
- [Security in depth](https://docs.altinn.studio/technology/architecture/principles/#security-in-depth). Se chapter above.


## How this could be implemented

1. We create a new container with headless chromium and a [simple API](https://github.com/browserless/chrome/blob/master/functions/pdf.js#L56) for returning PDF based on an URL.
   - We could use the open source [browserless container image](https://github.com/browserless/chrome) for a first proof of concept.
   - [Here](https://medium.com/compass-true-north/go-service-to-convert-web-pages-to-pdf-using-headless-chrome-5fd9ffbae1af) is also some Go-based inspiration
2. The API is used by app backend, in a similar way as app backend today calls altinn-pdf, except that the input is an app instance URL and cookie.
3. App backend stores the PDF in Storage, just as today. The PDF container should not have access to Platform APIs.
4. To be able to store everything in a PDF we need to create a new "everything-view" in app-frontend, that concatinates all pages and applies all dynamics.
   - This is something the Studio team need to do anyways to be able to answer the "what did I submit as a user?" question for archived apps.
   - Other pages like Summary, Receipt, Payment, etc. can also be convertable to PDF in the same way, all we need is an URL

## Risks
- Performance and time used for rendering. How fast is headless chromium? 
- Security, isolation between user sessions i Chrome
- Stability, Chrome can be a hog and a beast

**Comment by ivarne** [comment]
@altinnadmin Great writeup!

We considered the performance and stability issues when solving the same issue at UDI, and our architect used ServiceBus to ensure that we could do a series of async opreations on different azure functions with proper retry, and also the possibility of saying OK to the user and process the pdf generation backlog at a later time.

**Comment by TheTechArch** [comment]
I believe that some orgs would want to create their PDF view not based on an automatic merging of all pages. There are probably lots of services that want a different "custom view". Should this be covered?

**Comment by altinnadmin** [comment]
> There are probably lots of services that want a different "custom view". Should this be covered?

Yes, if that's a need we could add config, so that for example the Summary page could be used instead, or perhaps in addition.
Remember that the user probably has a need to be able to see everything regardless of the need of the app owner.

Ref. bullet 4 above:
*"Other pages like Summary, Receipt, Payment, etc. can also be convertable to PDF in the same way, all we need is an URL"*

**Comment by ivarne** [comment]
> Yes, if that's a need we could add config

Or a reasonable extention point where app devs can add their own logic for generating artefacts at appropriate times. Config can come later when we want to make it possible to do in Altinn Studio.

**Comment by ddrune** [comment]
@SandGrainOne , @altinnadmin 
I know of some good alternatives that offer sandboxing through either containerization, file-based ingress/egress or use through APIs. The famous and extensive [`pandoc`](https://hackage.haskell.org/package/pandoc-2.18/docs/Text-Pandoc-PDF.html) framework use `xelatex` (i.e [`XeTeX`](https://en.wikipedia.org/wiki/XeTeX)) - but through LaTeX-format and files (UNIX philosophy). But interestingly `pandoc` also use [`prince`](https://en.wikipedia.org/wiki/Prince_(software)), which is free to non-commercial - while [governmental use](https://www.princexml.com/purchase/) has a fee. They are also [governed under Norwegian license](https://www.princexml.com/purchase/license_faq/) law. They offer supreme [PDF/UA capabilities](https://www.princexml.com/doc/prince-output/#pdfua) as well, and [file-based ingress/egress](https://www.princexml.com/doc/command-line/).

**Comment by altinnadmin** [comment]
Thanks @ddrune . I had a look at the wikipedia page for Prince:

> CSS Grid Layout (css-grid-1) is not yet present in Prince 14.

and 

> Prince supports most of ECMAScript 5th edition, but not strict mode. Later editions of ECMAScript are largely not supported.

I don't think prince is able to fulfill our first principle, PDF generation should "just work",  given that our apps are modern React-applications. A lot has happened since the 5th edition of ecmascript was released way back in 2009.

**Comment by SandGrainOne** [comment]
We eventuelly landed on using latest version browserless/chrome from browserless.io. This will be hosted together with the application owner apps in the app owner spesific AKS. I suspect that we would want to eventually replace it with something where we have more direct control, but for now this issue is being closed as completed.
