### ISSUE TITLE
Roll-out of platform PDF instance to all environments

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-pdf#66]
### Description
We want the new PDF generator to be deployed to all environments. The release pipeline https://dev.azure.com/brreg/altinn-studio/_release?_a=releases&view=all&definitionId=54 must be expanded with stages for all environments

### Tasks
-  [x] Update release pipeline to include stages for all environments

**Comment by Ahmed-Ghanam** [comment]
The new generator has been deployed to AT21, AT22, AT23, AT24, YT01, TT02, and PROD. Since there isn't a straightforward way to test this feature across all environments, it's recommended to close this ticket and address any issues that may arise in the future.


The release pipeline shows two warnings:
2024-08-29T10:09:00.1974848Z ##[warning]Task 'Helm tool installer' version 0 (HelmInstaller@0) is deprecated.
2024-08-29T10:09:00.1982373Z ##[warning]The HelmInstaller@0 task is deprecated, please use a newer version of the HelmInstaller task
Shall we do update/use another tool?
This task has its own ticket now here. #68

**Comment by acn-sbuad** [comment]
PDF generation verified in AT24. Verified all pods running ok in all AT envs.
Verification of YT, TT and Prod remaining

**Comment by acn-sbuad** [comment]
Verified in remaining environments
